frontend/src/components/commons/divider/HorizontalDivider.tsx, frontend/src/components/commons/divider/VerticalDivider.tsx, frontend/tailwind.config.js
> #37
- 수직, 수평 Divider 컴포넌트 구현
=> 공용 divider 컴포넌트 구현

backend/.gitignore, backend/package.json, backend/src/app.module.ts, backend/src/edge/edge.controller.spec.ts, backend/src/edge/edge.controller.ts, backend/src/edge/edge.entity.ts, backend/src/edge/edge.module.ts, backend/src/edge/edge.repository.ts, backend/src/edge/edge.service.spec.ts, backend/src/edge/edge.service.ts, backend/src/node/node.controller.spec.ts, backend/src/node/node.controller.ts, backend/src/node/node.entity.ts, backend/src/node/node.module.ts, backend/src/node/node.repository.ts, backend/src/node/node.service.spec.ts, backend/src/node/node.service.ts, backend/src/page/page.controller.spec.ts, backend/src/page/page.controller.ts, backend/src/page/page.entity.ts, backend/src/page/page.module.ts, backend/src/page/page.repository.ts, backend/src/page/page.service.spec.ts, backend/src/page/page.service.ts, backend/yarn.lock
| #29 
- 따로 이슈를 적어놨어야 했는데 누락했습니다...
- 엔티티 설계를 하고, TypeORM 설정을 해두었습니다.
- 컨트롤러 / 서비스 / 레포지토리 로직을 바로 작성할 수 있게 세팅해두었습니다.
- 따로 API를 작성하지는 않았습니다...
```mermaid
erDiagram
PAGE ||--|| NODE : "has"
NODE ||--o{ EDGE : "from"
NODE ||--o{ EDGE : "to"
PAGE {
int id PK
string title
json content
}
NODE {
int id PK
float x
float y
int page_id FK
}
EDGE {
int id PK
int from_node_id FK
int to_node_id FK
enum from_point
enum to_point
enum type
enum color
}
```
- 우선 임의대로 `sqlite`를 개발용 db로 사용하도록 했는데요. 개발 중 `postgres` 가 제공하는 기능이 필요하다면, 로컬용 도커 설정을 해두는 것도 방법일 것 같습니다.
- `jsonb` 타입을 사용하여 json의 키로 인덱싱을 해야 한다던가...
- 임시로 [일지](https://tolerblanc.notion.site/CRUD-135cb187720a8017ac96eb7a05c37080?pvs=4)를 작성하면서 커밋했는데, 진행했던 내용을 내일 설명드리면서 시간 날 때 wiki로 옮겨놓겠습니다.
=> TypeORM 설정 & Entity 설계

frontend/package.json, frontend/src/App.tsx, frontend/src/components/editor/content.ts, frontend/src/components/editor/extensions.ts, frontend/src/components/editor/index.tsx, frontend/src/components/editor/prosemirror.css, frontend/src/components/editor/slash-commands.tsx, frontend/src/components/layout/SideWrapper.tsx, frontend/tailwind.config.js, frontend/yarn.lock
> #6 
- 에디터 컴포넌트 추가
- prose 스타일 설정
- `<SideWrapper />` 컴포넌트 구현
=> 에디터 컴포넌트 추가

.github/workflows/deploy.sh, .github/workflows/main.yml
#31 
- Nest.js 서버 NCloud Server 자동 배포 구현
- React 빌드 파일 NCloud Object Storage 자동 배포 구현
현재 Nest.js 서버 자동 배포까지는 확인되었고 리액트 자동 배포는 아직 확인 못 했습니다.
내일 프론트, 백엔드 main에 병합 후 제 PR 승인하여 테스트를 해봐야 할 것 같습니다.
=> feat: cicd workflow 작성

frontend/package.json, frontend/src/App.tsx, frontend/src/api/node.ts, frontend/src/api/page.ts, frontend/src/components/EditorView.tsx, frontend/src/components/editor/index.tsx, frontend/src/components/sidebar/NoteList.tsx, frontend/src/components/sidebar/Tools.tsx, frontend/src/components/sidebar/index.tsx, frontend/src/hooks/useNodes.ts, frontend/src/hooks/usePages.ts, frontend/src/lib/axios.ts, frontend/src/store/usePageStore.ts, frontend/yarn.lock
> #54 
- axios 유틸 함수 구현
- node, page api 구현
- node, page query, mutation 구현
- page 스토어 구현
- 선택한 노트의 에디터 불러오기 / 저장하기
- 페이지 추가 버튼 구현
=> 에디터 query, mutation 관련 기능 구현

README.md
> #61 
> `Readme.md`에 프로젝트 소개, 팀원 소개 복구
=> docs: 프로젝트 소개, 팀원 소개 복구

backend/src/node/node.module.ts, backend/src/node/node.service.ts, backend/src/page/page.entity.ts, backend/src/page/page.module.ts, backend/src/page/page.service.ts
=> fix: node <-> page 순환참조 문제 해결

frontend/src/api/page.ts, frontend/src/components/editor/index.tsx, frontend/src/hooks/usePages.ts
> #66 
- 에디터 content 자동 저장 구현
- 자동 저장 상태 표시 기능 추가
=> 에디터 content 자동 저장 기능 추가

README.md
> #73 
- `README.md`에 hits 카운터 추가
>
> 이왕이면 빨리 추가하는게 좋을 것 같아서 넣어봤습니다.
=> docs: README에 hits 카운터 추가

backend/src/exception/edge.exception.ts, backend/src/filter/http-exception.filter.ts, backend/src/main.ts
> close #56 
- 커스텀 예외 필터 작성 + 글로벌로 적용
- 컨벤션 용도로 예시 예외 하나 작성
=> 커스텀 예외 필터 구현

backend/src/exception/node.exception.ts, backend/src/exception/page.exception.ts, backend/src/node/node.controller.ts, backend/src/node/node.service.ts, backend/src/page/page.controller.ts, backend/src/page/page.service.ts
#56     
- service, controller에 있던 try-catch 부분을 삭제
- 에러처리가 필요한 경우 커스텀 에러로 throw하게 함    
- create, save가 공통으로 나타나는 것을 save 하나로 통일
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
=> try-catch 제거, custom error 추가

backend/src/edge/edge.controller.spec.ts, backend/src/edge/edge.service.spec.ts, backend/src/node/node.controller.spec.ts, backend/src/node/node.controller.ts, backend/src/node/node.service.spec.ts, backend/src/node/node.service.ts, backend/src/page/page.controller.spec.ts, backend/src/page/page.controller.ts, backend/src/page/page.service.spec.ts, backend/src/page/page.service.ts
=> node, page : controller, service 테스트 코드 작성

frontend/src/api/node.ts, frontend/src/api/page.ts, frontend/src/components/EditorView.tsx, frontend/src/components/canvas/index.tsx, frontend/src/components/editor/EditorView.tsx, frontend/src/components/sidebar/NoteList.tsx, frontend/src/components/sidebar/Tools.tsx, frontend/src/hooks/useNodes.ts, frontend/src/hooks/useNoteList.ts, frontend/src/hooks/usePages.ts
- closes #107 
- API 명세 변경에 따른 쿼리 수정
=> API 명세 변경에 따른 쿼리 수정

frontend/package.json, frontend/src/components/editor/EditorTitle.tsx, frontend/src/components/editor/EditorView.tsx, frontend/src/components/editor/index.tsx, frontend/src/index.css, frontend/yarn.lock
- #109 
yjs와 웹소켓으로 에디터 동시 편집 기능을 추가했습니다.
=> yjs와 웹소켓을 이용한 동시 편집 기능 추가

backend/src/node/node.controller.ts, backend/src/node/node.service.spec.ts, backend/src/page/page.controller.spec.ts, backend/src/page/page.entity.ts, backend/src/page/page.service.spec.ts
Closes #124
- createdAt, updatedAt, version 추가 (typeORM이 자동으로 관리해주는듯)
- node test code에 에러 있길래 고쳤습니다 모킹 대상이 잘못됐더라고요
=> Page DB Column 추가

frontend/src/components/editor/ui/command.tsx
=> lint 에러 수정 

frontend/src/hooks/useYText.ts
=> lint 오류 해결

backend/src/edge/edge.service.spec.ts, backend/src/edge/edge.service.ts
- closes #150 
- 절대경로 import를 상대경로로 수정
- 의존성 mocking 빠진 부분 해결
=> 백엔드 단위테스트가 실패하는 문제

.github/workflows/auto-assign-merge.yml
- closes #148 
- assignee와 reviewer는 PR 이벤트에만 동작하도록 수정
- 오토 머지는 Approve 상태가 되었을 때만 동작하도록 수정
=> CI 스크립트(자동 병합, 리뷰어 지정) 실행 시점 수정

.github/workflows/main.yml
- #156 
github secrets에 등록된 .env 파일을 프론트엔드에 디렉토리에 넣어주었습니다.
=> fix: DEVELOPMENT_FE_ENV 추가

frontend/src/components/canvas/index.tsx
- #153 
- 개별 노드로 움직이게 수정
- 새로운 pages로 노드 업데이트하게 수정
https://github.com/user-attachments/assets/20a7c37b-cb0a-4020-9f58-8c103e48defe
=> 노드들이 한번에 움직이는 문제 수정

frontend/src/components/EditorView.tsx
- fixes #163
- 에디터 컴포넌트의 디버깅용 텍스트 제거
- 데모 이후에는 에러/로딩 상태를 구현해야 합니당
=> 에디터 컴포넌트의 디버깅용 텍스트 제거

README.md
- closes #175 
- 문어 만들기
- 프로젝트 소개 이미지 수정
- 쉬면서 만들어봤는데 어떤가요? 🐙
=> README에 문어 추가

README.md
- #179 
- wiki, backlog 뱃지 추가
- 추후 수정 가능
=> wiki, backlog 뱃지 추가

frontend/src/components/editor/EditorTitle.tsx, frontend/src/components/editor/prosemirror.css, frontend/src/components/layout/EditorLayout.tsx
- closes #181 
- 노션의 기본 텍스트, H1, H2, H3 참고.
- `font-size`, `line-height`, `font-weight` 수정.
- `margin`, `padding` 수정.
- 나중에 다른 태그들도 틈틈이 수정해줘야 할 것 같아요! 생각보다 오래걸리네요..
- `bug-#177` 브랜치에서 만들어서.. `EditorLayout`도 들어가 있는데.. 무시해주세요..
=> 에디터 텍스트, 간격 스타일링

.gitignore, apps/backend/src/edge/dtos/createEdge.dto.ts, apps/backend/src/edge/dtos/findEdgesResponse.dto.ts, apps/backend/src/edge/edge.entity.ts, apps/backend/src/edge/edge.service.ts
Closes #190 
- FE에서 다른 노드의 상대적 위치에 따라 Direction 자동으로 선택
- DB에서 Edge의 toPoint, fromPoint(Direction) 기록하지 않아도 됨
=> 엣지 API, DB 스키마 업데이트

.github/workflows/auto-assign-merge.yml
- closes #168 
- 자동 머지 실행 조건 개선
- 실패하는 경우에 대해 자세히 로그를 찍도록 수정
=> 자동 머지 조건 및 세부동작 수정

apps/backend/package.json, apps/backend/src/edge/edge.module.ts, apps/backend/src/edge/edge.service.ts, apps/backend/src/yjs/yjs.module.ts, apps/backend/src/yjs/yjs.service.ts
- #198 
- node 변경 사항 감지 및 저장
- edge 변경 사항 감지 및 저장
- page 변경 사항 감지 및 저장
=> node, edge, page 변경 사항 감지 및 데이터베이스 저장

apps/backend/src/node-cache/node-cache.service.ts, apps/backend/src/yjs/yjs.schema.ts, apps/backend/src/yjs/yjs.service.ts, apps/backend/src/yjs/yjs.type.ts
- Closes #226 
- Closes #231
- 페어프로그래밍을 통해 `isHolding` 필드 핸들링 -> 쿼리 업데이트 요청 수를 줄임
- YJS에 `image` 스키마 추가
=> 업데이트 쿼리 디바운싱

apps/frontend/src/components/canvas/NoteNode.tsx, apps/frontend/src/components/commons/emoji/index.tsx, apps/frontend/src/components/editor/EditorTitle.tsx, apps/frontend/src/components/sidebar/NoteList.tsx
- closes #245
emoji가 null일 때, placeholder 구현
https://github.com/user-attachments/assets/082696d1-59e9-416d-b084-7ef7e5fc1c49
=> 이모지 placeholder UI 구현

apps/backend/package.json, apps/backend/src/auth/auth.controller.spec.ts, apps/backend/src/auth/auth.controller.ts, apps/backend/src/auth/auth.module.ts, apps/backend/src/auth/auth.service.spec.ts, apps/backend/src/auth/guards/jwt-auth.guard.ts, apps/backend/src/auth/guards/jwtauth.guards.ts, apps/backend/src/exception/invalid.exception.ts, apps/backend/src/exception/login.exception.ts, apps/backend/src/exception/user.exception.ts, yarn.lock
- Closes #215
- 로그인 성공 후 JWT 토큰 생성
- 로그인 요구하는 엔드포인트 접근 시 토큰 확인
=> JWT 인증, 인가  
