backend/src/node/node.controller.ts
backend/src/node/node.repository.ts
backend/src/node/node.service.spec.ts
backend/src/node/node.service.ts

close #20 
- 특정 노드의 ID를 받아 좌표를 반환하는 API 구현 (`GET /node/:id/coordinates`)
- 최대한 간단한 형태로 구현해보았습니다.
- TODO 주석으로 달았지만, `:id` 파라미터가 잘못 넘어왔을 때의 처리를 컨벤션으로 통일해야 할 것 같습니다.
- 없는 엔드포인트는 확실히 **404**가 맞지만, 성공한 요청이 null을 보낼 때 또한 **404**로 처리해야 할까요?

노드 좌표 반환 API 구현

---

backend/src/page/page.controller.ts
backend/src/page/page.repository.ts
backend/src/page/page.service.spec.ts
backend/src/page/page.service.ts

close #19 
- 데이터베이스에 존재하는 모든 페이지를 반환하는 API를 구현했습니다.
- 추후 워크스페이스 개념을 도입하면, 파라미터 `:workspace_id` 를 통해 필터링하여 반환하는 로직으로 수정이 필요합니다. 
- 너무 간단한 것 같은데 이 의도로 작성된 이슈가 맞을까요...? #18 이랑 무슨 차이가 있나요??

페이지 목록 반환 API 구현

---

frontend/src/components/canvas/NoteNode.tsx
frontend/src/components/canvas/index.tsx

> #51 
- `NoteNode` 타입 및 `<NoteNode />` 커스텀 컴포넌트 구현
-  `usePages()` 쿼리 결과로 노드 렌더링

NoteNode 타입 및 커스텀 컴포넌트 구현, 쿼리 결과로 노드 렌더링 구현

---

frontend/src/components/commons/button/index.tsx
frontend/src/components/sidebar/NoteList.tsx
frontend/src/components/sidebar/Tools.tsx

- fixes #53 
- `<Button />` 컴포넌트에 `select-none` 추가
- `<Sidebar />` 컴포넌트에서 수정된 `<Button />` 사용하게 변경
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

Sidebar 컴포넌트에서 text 선택이 불가능하게 수정

---

frontend/src/components/sidebar/NoteList.tsx

- fixes #83
- 사이드바 페이지 목록 text `overflow` 수정
- 나중에 `<Button />` 자체에 넣어야할 것 같긴 해요..!

사이드바 페이지 목록 text overflow 수정

---

frontend/package.json
frontend/src/components/cursor/index.tsx
frontend/yarn.lock

- closes #86 
- 커서 SVG 만들기
- framer-motion 추가
- prop으로 받은 x, y 좌표에 위치하는 기본 커서 컴포넌트 구현
https://github.com/user-attachments/assets/323d36fa-14c9-44c6-8ad9-a7a86c7defb6
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
- https://github.com/djk01281/live-share/blob/main/app/editor/components/Cursor/index.tsx

기본 커서 컴포넌트 추가

---

frontend/src/hooks/useNoteList.ts
frontend/src/store/usePageStore.ts

> #75 
에디터 삭제 시 currentPage를 null로 설정해서 에디터를 닫는다.
https://github.com/user-attachments/assets/b1f60ed6-77e5-4c98-8c82-6fcf6f2f6d82

fix: 페이지 삭제시 에디터 내용이 바뀌지 않는 문제

---

frontend/src/App.tsx
frontend/src/components/editor/EditorTitle.tsx
frontend/src/components/editor/EditorView.tsx
frontend/src/components/editor/index.tsx
frontend/src/components/editor/ui/SaveStatus.tsx
frontend/src/components/layout/EditorLayout.tsx
frontend/src/hooks/usePages.ts

- closes #81 
- optimistic하게 업데이트하는 페이지 mutation hook 구현
- `<Title />` 컴포넌트 구현
https://github.com/user-attachments/assets/493c1032-4293-47aa-9235-848bee3a0683
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
쿼리 `type`을 같이 전체적으로 손을 보긴 해야할 것 같긴 한데.. 소켓 로직 들어가면 덮어 씌워질 거라 고민이 되네용.

EditorTitle 컴포넌트 추가

---

.github/workflows/main.yml
deploy.sh

- #136
.env 파일은 .gitignore에 등록되어 깃허브에 올라가지 않습니다.
.env 파일을 github action secrets에 등록하고 push가 발생했을 때 .env 파일을 원격 서버로 전송합니다.
그 후 deploy.sh도 원격 서버로 보내서 쉘 스크립트 파일을 실행합니다.
deploy.sh는 github에서 최신 변경 사항을 가져온 다음 3000번 포트에 서버를 띄웁니다.
- .
지금 뭔가 CD를 야매로 한 것 같아서 걱정이 되네요.
git에서 최신 정보를 pull 해 올 경우 .env 파일이 없어서 데이터베이스 연동이 안됩니다.
이를 해결하기 위해 github action secrets에 .env를 등록한 다음 이 .env 파일을 원격 서버로 보내도록 하고 있습니다.
.env 파일을 노출시키지 않으면서 CD를 구축하기 위해 선택한 방법인데 혹시 다른 좋은 방법 있으시다면 공유해주시면 감사하겠습니다!!

.env 파일 전송

---

frontend/src/components/editor/index.tsx

- closes #139 
`EditorContent`에서 `initialContent`와 `CollaborationCursor`와 충돌이 있는 거 같아서 `initialContent` 를 제거했다.

에디터 추가 시, 커서 익스텐션과 충돌나는 문제 해결

---

frontend/src/components/EditorView.tsx
frontend/src/components/canvas/index.tsx

- closes #141 
`import.meta.env.VITE_WS_URL` 와 같이 환경 변수로 URL을 관리헀습니다.

환경 변수를 통한 API 및 웹 서버 URL 관리

---

backend/src/main.ts

- #144 
- dotenv에 origin을 등록하고 해당하는 origin만 CORS를 허용해주었습니다.

feat: dotenv에서 CORS 허용할 origin 등록

---

frontend/package.json
frontend/src/components/EditorView.tsx
frontend/src/components/canvas/index.tsx
frontend/src/components/editor/EditorTitle.tsx
frontend/src/hooks/useYText.ts
frontend/src/store/useYDocStore.ts
frontend/yarn.lock

- closes #146 
- Y.Doc을 Global State로 관리한다.
- 이 전역 Y.Doc는 에디터와 캔버스에서 공유된다.
- Y.Doc에 Y.Text를 추가하여 에디터 제목을 실시간 동시 편집이 가능하게 한다.
https://github.com/user-attachments/assets/4e42845c-f49d-44f5-ab5c-f1ddbfaa2ebe
랜덤으로 노드 위치가 바뀌는 문제는 추후 수정할 예정

에디터 업데이트 시 노드에 반영하는 기능 추가

---

.github/workflows/main.yml
deploy.sh

- #143 
기존에는 최신 코드 받아오고 프로세스 실행하는 과정이 쉘 스크립트 파일로 이루어져 그 과정이 기록되지 않았습니다.
만약 쉘 스크립트 파일 실행이 실패하더라도 workflow는 성공한 것으로 나와서 결과 확인이 어려웠습니다.
그래서 sh 파일을 서버로 보내서 실행하는 것이 아니라 ssh 명령어를 통해 직접 원격 서버 명령어를 실행하도록 구현했습니다.
즉 directory 생성, git pull, 기존 프로세스 종료의 과정이 로깅됩니다.
하지만 그 후 마지막에 yarn start로 서버를 킬 때는 백그라운드로 실행되기 때문에 이 과정은 로깅되지 않습니다.
- sh 파일 전송 제거
- ssh 명령어 사용
**로깅 과정**
**아쉽게도 서버 실행은 로깅되지 않습니다.**

서버 배포 과정 로깅

---

frontend/src/App.tsx
frontend/src/components/layout/ScrollWrapper.tsx

- fixes #161 
- 사이드바에 ScrollWrapper 적용

사이드바에 ScrollWrapper 적용

---

frontend/src/App.tsx
frontend/src/components/layout/EditorLayout.tsx
frontend/src/components/layout/SideWrapper.tsx
frontend/src/store/usePageStore.ts

- closes #165 
- `usePageStore`에 `isPanelOpen` 추가
- 같은 페이지를 선택 시, 패널이 열려있었다면 닫히게, 닫혀 있었다면 열리게 구현
- `<Sidebar />` 컴포넌트가 패널 버튼을 가리지 않게 `z-index` 수정
- 패널이 닫혔을 때 전체 화면에 스크롤바가 생기는 이슈, 아래의 element에 접근 못하게 하는 이슈 수정
https://github.com/user-attachments/assets/c0dcb9fa-da48-472e-a705-8b524d9b1215

에디터에 패널 open/close 기능 추가

---

frontend/src/components/canvas/index.tsx

- fixes #171 
- 첫 렌더링 시에는 `Y.Doc` 이벤트 `observe` 하지 않게 수정
**설명**
-  첫 렌더일 때는 `observe` 하지 않게 수정 (그러지 않으면 처음에 `pages`를 가져와서 `nodesMap`에 하나씩 넣을 때 모두 변경 이벤트로 받아들여서 `invalidate` 합니다.)

첫 렌더링 시 pages 쿼리 중복 요청 수정

---

frontend/src/components/layout/EditorLayout.tsx

- #177 
- `translate-x-0` 때문에 stacking context가 생성, `position: fixed`인 `<dragHandle />`이 이에 영향을 받는 문제를 `translate-none` 으로 변경해서 수정.
> **`transform`**:  If the property has a value different from none, a [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index/Stacking_context) will be created. In that case, the element will act as a [containing block](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block) for any position: fixed; or position: absolute; elements that it contains. (https://developer.mozilla.org/en-US/docs/Web/CSS/transform)

에디터 블록 drag handle이 예상과 다른 곳에 위치하는 문제 수정

---

apps/frontend/src/components/canvas/index.tsx

- closes #207 
- Y.Doc의 `node`에 `isHolding` property 추가.
- `dragStop` 시, `false`로 설정해서 보내기.
- `isHolding`입니다. 어떻게 고쳐도 마지막에 `false`로 2번을 보내네요.. 사실 디바운싱이 목적이었으니까 일단은 이것으로 충분하지 않을까 싶긴 합니다..
- `Object.entries()` 와 `filter()`를 사용한 부분이 있는데, eslint rule과 싸워서 빌드 성공하기 위한 엄청난 사투가 있었습니다.. 😇 원래 원했던 것 : `const initialNodes = yNodes.map(({ isHolding, ...node }) => node);`

Y.Doc의 node에 isHolding property 추가

---

apps/frontend/src/App.tsx
apps/frontend/src/components/CursorView.tsx
apps/frontend/src/components/EditorView.tsx
apps/frontend/src/components/canvas/NoteNode.tsx
apps/frontend/src/components/commons/activeUser/index.tsx
apps/frontend/src/components/cursor/index.tsx
apps/frontend/src/hooks/useCursor.ts
apps/frontend/src/hooks/useSyncedUsers.ts
apps/frontend/src/lib/utils.ts
apps/frontend/src/store/useUserStore.ts

- closes #206
- Client 룸 생성하기
- 유저 식별을 위한 랜덤 색상 및 clientId 생성 (로컬스토리지 이용)
- 에디터 접속 인원을 노드와 에디터에 보여주기
https://github.com/user-attachments/assets/1902239d-17ec-414c-81d1-eb2bb73dcb2e
일단 디자인은 최대한 간단하게 했습니다. (추후 수정을 위해)
궁금한 게 하나 있는데, 자신의 접속 현황은 표시를 안하는 게 자연스러울까요??
1. 에디터(content)에서 클라이언트를 일관되게 보여주기 (에디터 마다 다른 웹 소켓 Room에 접속해서)
2. 중복 탭 문제 -> 클라이언트 id가 같은 접속 현황이 여러 개 보여지게 됨
3. 이미 접속중인 `clientId` 가 있으면 이전 연결을 끊고, 새로운 연결을 해야 할 거 같습니다! (새로고침하면 flow-room에 다시 연결돼서 컴포넌트 `key` 문제가 생깁니다.

유저를 관리하기 위한 웹소켓 Room 추가

---

apps/frontend/src/components/EditorView.tsx
apps/frontend/src/components/editor/EditorActionPanel.tsx
apps/frontend/src/components/editor/EditorTitle.tsx
apps/frontend/src/components/editor/prosemirror.css
apps/frontend/src/components/editor/ui/SaveStatus.tsx
apps/frontend/src/components/layout/EditorLayout.tsx
apps/frontend/src/store/usePageStore.ts

- closes #212 
- 에디터 전체 화면 기능 구현
- 에디터 닫는 버튼 유동적으로 변경(에디터가 열려 있을 때는 에디터 안으로 이동) 구현
https://github.com/user-attachments/assets/920a05dc-1527-4008-9578-5560dd994ac2

에디터 전체화면 기능 

---

apps/backend/src/yjs/yjs.service.ts

- #223 
- document 파싱 이슈 해결
document-1 에서 숫자를 파싱하지 못 하는 이슈였습니다.
```
if (customDoc.name !== 'flow-room')
```
기존에는 flow-room과 document-숫자 밖에 없어서 문제가 없었지만 users가 추가되면서 발생한 이슈입니다.
"document-"로 시작할 때만 파싱하도록 변경했습니다.
```
if (customDoc.name?.startsWith('document-')) {
```

document name 파싱 이슈 해결

---

.github/workflows/develop.yml
apps/frontend/package.json

- #235 
- 프론트엔드 package.json에 homepage 추가
- 개발, 상용 배포 환경 분리
로컬 개발 환경과 원격 환경의 코드가 동일함에도 정적 파일에서 오류가 발생했습니다.
기본적으로 리액트를 빌드할 때 루트 디렉토리를 기준으로 한다고 합니다. 
homepage로 이 디렉토리를 바꿔주어 에러를 해결했습니다.

Bug be #235

---

apps/frontend/src/components/editor/index.tsx

- closes #239 
에디터 provider의 awareness에 setLocalStateField로 유저 정보를 전달해준다.
https://github.com/user-attachments/assets/1d388cd3-677c-4136-b052-3222ed47b5f5

에디터 커서에 유저 정보 보여주는 기능 구현
